format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$character
"""

right_format = """
$cmd_duration\
${custom.vifm}
"""

[directory]
style = "blue"
# read_only = " î‚¢"

[character]
success_symbol = "[\\$](white)"
error_symbol = "[\\$](red)"
vicmd_symbol = "[\\$](green)"

[git_commit]
only_detached = true
commit_hash_length = 8
tag_disabled = false
tag_symbol = "ğŸ· "
format = "( [@](white)[($hash$tag)](green))"

[git_branch]
format = "[($symbol$branch)]($style)"
style = "green"

[git_status]
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = 'â‡•\[â‡¡${ahead_count} â‡£${behind_count}\]'
conflicted = "[(!$count)](16) "
untracked = "([â‹…$count](yellow) )"
modified = "([Â±$count](5) )"
staged = "([+$count](blue) )"
renamed = "([â¥$count](green) )"
deleted = "([âŒ§ $count](bold red) )"
stashed = "([ïŒ¹ $count](16) )"
format = "[( $ahead$conflicted$staged$untracked$modified$renamed$deleted$stashed$ahead_behind)](white)"

[git_state]
cherry_pick = "[cherry](bold red)"
format = ' \([$state($progress_current/$progress_total)]($style)\)'

[git_metrics]
added_style = "bold blue"
format = '(\[([+$added]($added_style))( [-$deleted]($deleted_style))\])'
disabled = false

[cmd_duration]
format = "([$duration]($style) )"
style = "247"

[custom.vifm]
description = "Checks if shell was launched from vifm"
when = "[[ -v INSIDE_VIFM ]]"
shell = ["zsh", "-df"]
format = '[ïˆ](yellow)'
